$ErrorActionPreference = "Stop"

scoop install act
scoop install ah
scoop install aws
scoop install aws-iam-authenticator
scoop install azure-cli
scoop install azure-kubelogin
scoop install buf
scoop install caffeine
scoop install chezmoi
scoop install conftest
scoop install cosign
scoop install dark
scoop install dependency-check
scoop install dua
scoop install duf
scoop install editorconfig
scoop install eksctl
scoop install envsubst
scoop install firacode-nf
scoop install firacode-nf-mono
scoop install fluxctl
scoop install fzf
scoop install gdu
scoop install gh
scoop install gitsign
scoop install go
scoop install go-containerregistry
scoop install go-jsonnet
scoop install gomplate
scoop install gpg
scoop install gradle
scoop install graphviz
scoop install grep
scoop install gsudo
scoop install hadolint
scoop install helm
scoop install helm-chart-releaser
scoop install helm-chart-testing
scoop install helm-docs
scoop install hugo-extended
scoop install innounp
scoop install istioctl
scoop install jq
scoop install k6
scoop install k9s
scoop install kind
scoop install krew
scoop install kube-linter
scoop install kubeconform
scoop install kubectl
scoop install kubectx
scoop install kubefwd
scoop install kubens
scoop install kubescape
scoop install kubeval
scoop install kustomize
scoop install lessmsi
scoop install lxrunoffline
scoop install mage
scoop install make
scoop install maven
scoop install micro
scoop install nerdctl
scoop install nova
scoop install ntop
scoop install nuget
scoop install nvs
scoop install opa
scoop install openssl
scoop install oras
scoop install osv-scanner
scoop install pack
scoop install packer
scoop install pluto
scoop install pnpm
scoop install pulumi
scoop install python
scoop install regula
scoop install saml2aws
scoop install sed
scoop install sget
scoop install shellcheck
scoop install shfmt
scoop install sonar-scanner
scoop install sops
scoop install spdx-sbom-generator
scoop install starship
scoop install temurin17-jdk
scoop install terraform
scoop install terraform-docs
scoop install tflint
scoop install tfsec
scoop install upbound-cli
scoop install vale
scoop install vault
scoop install velero
scoop install yq
