#!/usr/bin/env bash

if command -v nano >/dev/null; then
  export EDITOR="nano"
else
  export EDITOR="vim"
fi
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

export HISTSIZE='32768'
export HISTFILESIZE="${HISTSIZE}"
export HISTCONTROL='ignoreboth'
