[settings]
default_target_type = "automatic"

[helpers]

[default]
depends = []

  [default.variables]
  codeDir      = "~/code"
  email        = "steve.hipwell@gmail.com"
  name         = "Steve Hipwell"
  sshKey       = "~/.ssh/id_ed25519"
  workCodeDirs = []
  workEmail    = "steve.hipwell@lexisnexisrisk.com"

  [default.files]
  editorconfig  = "~/.editorconfig"
  gitconfig     = "~/.gitconfig"
  gitconfigwork = "~/.gitconfigwork"
  shellcheckrc  = "~/.shellcheckrc"
  sshconfig     = "~/.ssh/config"
  starship      = "~/.config/starship.toml"

[bash]
depends = []

  [bash.variables]

  [bash.files]
  aliases      = "~/.aliases"
  bash_profile = "~/.bash_profile"
  bash_prompt  = "~/.bash_prompt"
  bashrc       = "~/.bashrc"
  exports      = "~/.exports"
  extra        = "~/.extra"
  functions    = "~/.functions"
  path         = "~/.path"

[powershell]
depends = []

  [powershell.variables]

  [powershell.files]
  powershell = "~/.config/profile.ps1"
